baseURL = ""
disableLanguages = []
disqusShortname = ""
paginate = "3"
summaryLength = "10"
theme = "galaxy"
title = "Galaxy | Hugo Personal Blog template"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
footer_menu_1 = "Inspirations"
footer_menu_2 = "Templates"
footer_menu_3 = "Resources"
footer_menu_4 = "Company"
home = "Home"
languageCode = "en-us"
languageName = "English"
weight = 1
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
footer_menu_1 = "Inspirations"
footer_menu_2 = "Templates"
footer_menu_3 = "Resources"
footer_menu_4 = "Company"
home = "Accueil"
languageCode = "fr-fr"
languageName = "French"
weight = 2
[markup.goldmark.renderer]
unsafe = true
[[menu.footer_1]]
URL = "privacy-policy"
name = "Privacy Policy"
weight = 1
[[menu.footer_1]]
URL = "about"
name = "Terms Conditions"
weight = 2
[[menu.footer_1]]
URL = "contact"
name = "Contact"
weight = 3
[[menu.footer_2]]
URL = "privacy-policy"
name = "Privacy Policy"
weight = 1
[[menu.footer_2]]
URL = "about"
name = "Terms Conditions"
weight = 2
[[menu.footer_2]]
URL = "contact"
name = "Contact"
weight = 3
[[menu.footer_3]]
URL = "privacy-policy"
name = "Privacy Policy"
weight = 1
[[menu.footer_3]]
URL = "about"
name = "Terms Conditions"
weight = 2
[[menu.footer_3]]
URL = "contact"
name = "Contact"
weight = 3
[[menu.footer_4]]
URL = "privacy-policy"
name = "Privacy Policy"
weight = 1
[[menu.footer_4]]
URL = "about"
name = "Terms Conditions"
weight = 2
[[menu.footer_4]]
URL = "contact"
name = "Contact"
weight = 3
[[menu.main]]
URL = "/"
name = "home"
weight = 1
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 3
[[menu.main]]
URL = "privacy-policy"
name = "Privacy Policy"
weight = 4
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
address = "9567 Turner Trace Apt. BC C3G8A4"
author = "Themefisher"
contact_form_action = "#"
description = "This is meta description"
email = "info@bexer.com"
google_analitycs_id = ""
image = "images/linkin_profile.png"
logo = "images/logo.png"
mobile = "+211234565523"
search = false
disableLanguageNav = true
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.subscription]
enable = true
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[[params.social]]
icon = "ti-facebook"
link = "#"
title = "facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
title = "twitter"
[[params.social]]
icon = "ti-instagram"
link = "#"
title = "instagram"
[[params.social]]
icon = "ti-github"
link = "#"
title = "github"
[[params.social]]
icon = "ti-linkedin"
link = "#"
title = "linkedin"
